import { useEffect, useMemo, useState } from "react";
import type { Channel } from "pusher-js";

import {
  UserChannelEvents,
  type BulkImportTenantMemberProgressEvent,
  type BulkImportTenantMemberRowResult,
} from "../types/userChannelEvents";

interface UseBulkImportProgressParams {
  /** User-level Pusher channel from useUserPusherChannel. */
  userChannel: Channel | null;
  /** Job ID generated by the caller; events with other job IDs are ignored. */
  jobId: string | null;
}

interface UseBulkImportProgressReturn {
  /** Per-row results keyed by 1-indexed row number, populated as events arrive. */
  rowResults: Map<number, BulkImportTenantMemberRowResult>;
  /** Number of rows finished (any status). Driven by the highest 'completed' seen. */
  completed: number;
  /** Total row count reported by the server in the most recent event. */
  total: number;
  /** Reset accumulated state (call when starting a new import). */
  reset: () => void;
}

/**
 * Subscribe to user-channel `bulk_import_progress` events and accumulate per-row
 * results live for the progress bar. Pusher is advisory — the HTTP response from
 * the bulk-import mutation is the canonical source of truth, so events dropped
 * mid-flight only stall the progress bar; the final results table is rebuilt
 * from the response on completion.
 */
export function useBulkImportProgress({
  userChannel,
  jobId,
}: UseBulkImportProgressParams): UseBulkImportProgressReturn {
  const [rowResults, setRowResults] = useState<
    Map<number, BulkImportTenantMemberRowResult>
  >(() => new Map());
  const [completed, setCompleted] = useState(0);
  const [total, setTotal] = useState(0);

  useEffect(() => {
    if (!userChannel || !jobId) return;

    const handler = (raw: string | BulkImportTenantMemberProgressEvent) => {
      const event: BulkImportTenantMemberProgressEvent =
        typeof raw === "string" ? JSON.parse(raw) : raw;
      if (event.jobId !== jobId) return;

      setRowResults((prev) => {
        const next = new Map(prev);
        next.set(event.result.row, event.result);
        return next;
      });
      // Trust the server's `completed` so out-of-order events don't double-count.
      setCompleted((prev) => Math.max(prev, event.completed));
      setTotal(event.total);
    };

    userChannel.bind(UserChannelEvents.BULK_IMPORT_PROGRESS, handler);
    return () => {
      userChannel.unbind(UserChannelEvents.BULK_IMPORT_PROGRESS, handler);
    };
  }, [userChannel, jobId]);

  const reset = useMemo(
    () => () => {
      setRowResults(new Map());
      setCompleted(0);
      setTotal(0);
    },
    [],
  );

  return { rowResults, completed, total, reset };
}
