import { useEffect, useState, useCallback } from "react";
import Pusher, { Channel } from "pusher-js";
import { useQueryClient } from "@tanstack/react-query";
import { getAccessToken } from "../lib/auth";

interface MessageCreatedEvent {
  conversationId: string;
  title: string;
  updatedAt: string;
}

/**
 * Hook to listen for conversation title updates via Pusher
 * When a title is generated by the backend, this hook updates the React Query cache
 * and provides the updated title for UI animation
 */
export function useConversationTitleUpdate(
  conversationId: string | null,
  pusherKey: string,
  pusherCluster: string,
  tenantId?: string,
  userId?: string,
) {
  const queryClient = useQueryClient();
  const [updatedTitle, setUpdatedTitle] = useState<string | null>(null);
  const [channel, setChannel] = useState<Channel | null>(null);

  useEffect(() => {
    if (
      !conversationId ||
      !pusherKey ||
      !pusherCluster ||
      !tenantId ||
      !userId
    ) {
      return;
    }

    // Get access token using centralized helper
    const token = getAccessToken();
    if (!token) {
      console.warn(
        "[useConversationTitleUpdate] No access token available - cannot authenticate Pusher",
      );
      return;
    }

    // Initialize Pusher
    const pusher = new Pusher(pusherKey, {
      cluster: pusherCluster,
      authEndpoint: `${import.meta.env.VITE_API_BASE_URL}/api/v1/pusher/auth`,
      auth: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
    });

    // Subscribe to the conversation channel
    const channelName = `private-vonlabs-chat-${tenantId}-${userId}-${conversationId}`;
    const pusherChannel = pusher.subscribe(channelName);

    setChannel(pusherChannel);

    // Listen for message_created event with title update
    const handleMessageCreated = (data: MessageCreatedEvent) => {
      if (import.meta.env.DEV) {
        console.log(
          "[useConversationTitleUpdate] Received message_created event:",
          data,
        );
      }

      if (data.conversationId === conversationId && data.title) {
        // Update the title state for animation
        setUpdatedTitle(data.title);

        // Invalidate conversations query to refetch with new title
        queryClient.invalidateQueries({ queryKey: ["conversations"] });

        if (import.meta.env.DEV) {
          console.log(
            "[useConversationTitleUpdate] Invalidated conversations cache, new title:",
            data.title,
          );
        }
      }
    };

    pusherChannel.bind("message_created", handleMessageCreated);

    // Cleanup
    return () => {
      pusherChannel.unbind("message_created", handleMessageCreated);
      pusher.unsubscribe(channelName);
      pusher.disconnect();
      setChannel(null);
    };
  }, [conversationId, pusherKey, pusherCluster, tenantId, userId, queryClient]);

  // Clear updated title after it's been shown
  const clearUpdatedTitle = useCallback(() => setUpdatedTitle(null), []);

  return {
    updatedTitle,
    clearUpdatedTitle,
    channel,
  };
}
