#!/usr/bin/env bash
# setup.sh — Install von-fe CLI to system PATH
#
# Usage: bash setup.sh
#
# What it does:
#   1. Makes bin/von-fe executable
#   2. Finds the active node binary (handles nvm, system node, homebrew)
#   3. Creates a wrapper at /usr/local/bin/von-fe (or ~/.local/bin/von-fe)
#      that calls node with the absolute path to bin/von-fe
#   4. If neither path is writable, appends the project bin/ to your shell profile

set -euo pipefail

# ── Resolve project root (directory containing this script) ───────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_SCRIPT="$SCRIPT_DIR/bin/von-fe"

# ── Colors ─────────────────────────────────────────────────────────────────────
CYAN='\033[1;36m'
GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
DIM='\033[2m'
RESET='\033[0m'

info()  { echo -e "  ${CYAN}von${RESET} $*"; }
ok()    { echo -e "   ${GREEN}ok${RESET} $*"; }
warn()  { echo -e " ${YELLOW}warn${RESET} $*"; }
error() { echo -e "  ${RED}err${RESET} $*"; }
die()   { error "$*"; exit 1; }

echo ""
echo -e "  ${CYAN}von-fe${RESET} — Frontend CLI installer"
echo ""

# ── Step 1: Make bin/von-fe executable ────────────────────────────────────────
if [[ ! -f "$BIN_SCRIPT" ]]; then
  die "bin/von-fe not found. Are you running this from the project root?"
fi

chmod +x "$BIN_SCRIPT"
ok "bin/von-fe is executable"

# ── Step 2: Find node binary ───────────────────────────────────────────────────
find_node() {
  # 1. Already in PATH
  if command -v node &>/dev/null; then
    command -v node
    return
  fi

  # 2. nvm default alias
  local NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
  if [[ -d "$NVM_DIR" ]]; then
    # Try the default alias first
    local nvm_default
    nvm_default=$(cat "$NVM_DIR/alias/default" 2>/dev/null | tr -d '[:space:]')
    if [[ -n "$nvm_default" ]]; then
      # Resolve 'lts/*' style aliases
      local resolved="$NVM_DIR/alias/$nvm_default"
      while [[ -f "$resolved" ]]; do
        nvm_default=$(cat "$resolved" | tr -d '[:space:]')
        resolved="$NVM_DIR/alias/$nvm_default"
      done
      local node_path
      node_path=$(ls "$NVM_DIR/versions/node/${nvm_default}/bin/node" 2>/dev/null || true)
      if [[ -f "$node_path" ]]; then
        echo "$node_path"
        return
      fi
    fi

    # Fallback: pick the highest installed version
    local latest
    latest=$(ls -d "$NVM_DIR/versions/node/"* 2>/dev/null | sort -V | tail -1)
    if [[ -n "$latest" && -f "$latest/bin/node" ]]; then
      echo "$latest/bin/node"
      return
    fi
  fi

  # 3. Homebrew
  for brew_node in /opt/homebrew/bin/node /usr/local/bin/node; do
    [[ -f "$brew_node" ]] && { echo "$brew_node"; return; }
  done

  echo ""
}

NODE_BIN=$(find_node)

if [[ -z "$NODE_BIN" ]]; then
  die "Could not find node. Install Node.js >= 22 via nvm (https://github.com/nvm-sh/nvm) or https://nodejs.org"
fi

NODE_VERSION=$("$NODE_BIN" --version 2>/dev/null || echo "unknown")
NODE_MAJOR="${NODE_VERSION#v}"
NODE_MAJOR="${NODE_MAJOR%%.*}"

if [[ "$NODE_MAJOR" -lt 22 ]] 2>/dev/null; then
  warn "Node ${NODE_VERSION} found — von-fe requires >= v22. Some features may not work."
else
  ok "Node ${NODE_VERSION} at ${DIM}${NODE_BIN}${RESET}"
fi

# ── Step 3: Create wrapper script ─────────────────────────────────────────────
WRAPPER_CONTENT="#!/usr/bin/env bash
# von-fe wrapper — auto-generated by setup.sh
# Project: $SCRIPT_DIR
exec \"$NODE_BIN\" \"$BIN_SCRIPT\" \"\$@\"
"

detect_shell_profile() {
  local shell_name
  shell_name="$(basename "${SHELL:-bash}")"
  case "$shell_name" in
    zsh)  echo "$HOME/.zshrc" ;;
    bash) echo "${BASH_PROFILE:-$HOME/.bash_profile}" ;;
    *)    echo "$HOME/.profile" ;;
  esac
}

ensure_in_path() {
  local dir="$1"
  local profile
  profile="$(detect_shell_profile)"
  local export_line="export PATH=\"\$PATH:$dir\""

  if echo "$PATH" | tr ':' '\n' | grep -qxF "$dir" 2>/dev/null; then
    return 0  # already active in current session
  fi

  if grep -qF "$dir" "$profile" 2>/dev/null; then
    ok "${DIM}${dir}${RESET} already in ${DIM}${profile}${RESET}"
  else
    echo "" >> "$profile"
    echo "# von-fe — Revenue OS Frontend CLI" >> "$profile"
    echo "$export_line" >> "$profile"
    ok "Added ${DIM}${dir}${RESET} to PATH in ${DIM}${profile}${RESET}"
    warn "Run: source $profile  (or open a new terminal)"
  fi
}

install_to() {
  local target_dir="$1"
  local wrapper="$target_dir/von-fe"

  if [[ ! -d "$target_dir" ]]; then
    mkdir -p "$target_dir" 2>/dev/null || return 1
  fi

  if [[ ! -w "$target_dir" ]]; then
    return 1
  fi

  echo "$WRAPPER_CONTENT" > "$wrapper"
  chmod +x "$wrapper"
  ok "Installed wrapper at ${DIM}${wrapper}${RESET}"
  return 0
}

INSTALLED=false

# Try /usr/local/bin first (system-wide, always in PATH)
if install_to "/usr/local/bin"; then
  INSTALLED=true
# Try ~/.local/bin (user-local) and ensure it's in PATH
elif install_to "$HOME/.local/bin"; then
  ensure_in_path "$HOME/.local/bin"
  INSTALLED=true
fi

# ── Step 4: Fallback — add project bin/ to shell profile ──────────────────────
if [[ "$INSTALLED" == "false" ]]; then
  warn "Could not write to /usr/local/bin or ~/.local/bin. Adding project bin/ to PATH instead."
  ensure_in_path "$SCRIPT_DIR/bin"
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}All done!${RESET} Try it:"
echo -e "  ${CYAN}von-fe help${RESET}"
echo ""
