/**
 * Event types for the user-level Pusher channel
 *
 * These events are sent to private-vonlabs-user-{tenantId}-{userId}
 * and received regardless of which page/conversation the user is viewing.
 */

/**
 * User channel event names - must match backend ConversationEvents constants
 * @see backend/private-packages/von-pusher-service/von_pusher_service/events.py
 */
export const UserChannelEvents = {
  CONVERSATION_TITLE_UPDATED: "conversation_title_updated",
  CONVERSATION_APPROVAL_PENDING: "conversation_approval_pending",
  CONVERSATION_APPROVAL_RESOLVED: "conversation_approval_resolved",
  CONVERSATION_APPROVAL_EXPIRED: "conversation_approval_expired",
  DASHBOARD_REFRESH_STARTED: "dashboard_refresh_started",
  DASHBOARD_REFRESH_COMPLETED: "dashboard_refresh_completed",
  BULK_IMPORT_PROGRESS: "bulk_import_progress",
  // Future events:
  // ORG_MEMORY_UPDATED: "org_memory_updated",
  // NOTIFICATION: "notification",
} as const;

export type UserChannelEventName =
  (typeof UserChannelEvents)[keyof typeof UserChannelEvents];

/**
 * Sent when a conversation title is generated by the backend
 */
export interface ConversationTitleUpdatedEvent {
  conversationId: string;
  title: string;
  updatedAt: string;
}

/**
 * Sent when an agent run in a conversation reaches a tool call awaiting user approval
 */
export interface ConversationApprovalPendingEvent {
  conversationId: string;
}

/**
 * Sent when a pending approval is resolved by user action (approved, rejected,
 * or the conversation was deleted while holding an approval). Expiry is its
 * own state transition — see ConversationApprovalExpiredEvent.
 */
export interface ConversationApprovalResolvedEvent {
  conversationId: string;
}

/**
 * Sent when a pending approval expires (TTL elapsed without a user decision).
 * This is a state transition, not a removal — the sidebar keeps an indicator
 * on the row, but switches it to the "expired" (orange→red) treatment.
 */
export interface ConversationApprovalExpiredEvent {
  conversationId: string;
}

/**
 * Sent when a dashboard refresh starts (background workflow initiated)
 */
export interface DashboardRefreshStartedEvent {
  dashboardId: string;
  executionId: string;
}

/**
 * Sent when a dashboard refresh completes (workflow finished successfully)
 */
export interface DashboardRefreshCompletedEvent {
  dashboardId: string;
  executionId: string;
  success: boolean;
}

/**
 * Sent when org memory/context is updated (future use)
 */
export interface OrgMemoryUpdatedEvent {
  updatedAt: string;
  updatedBy?: string;
}

/**
 * Generic notification event (future use)
 */
export interface NotificationEvent {
  type: "info" | "success" | "warning" | "error";
  message: string;
  action?: {
    label: string;
    url: string;
  };
}

/**
 * Per-row outcome from a bulk team-member import.
 * Mirrors the backend BulkImportRowResult schema.
 */
export interface BulkImportRowInput {
  firstName: string;
  lastName: string;
  email: string;
  role: string;
}

export interface BulkImportRowResult {
  row: number;
  input: BulkImportRowInput;
  status: "created" | "skipped" | "error";
  reason?: string | null;
  member?: {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
    role: string;
    joinedDate: string | null;
    isActive: boolean;
    usage: { total: number; last_week: number; last_month: number };
  } | null;
}

/**
 * Sent on the user channel as each row of a bulk team-member import finishes.
 * The HTTP response is the canonical source of truth — these events drive the
 * live progress bar and per-row table; if any are dropped, the response still
 * has every row classified.
 */
export interface BulkImportProgressEvent {
  jobId: string;
  completed: number;
  total: number;
  result: BulkImportRowResult;
}
