/**
 * Event types for the user-level Pusher channel
 *
 * These events are sent to private-vonlabs-user-{tenantId}-{userId}
 * and received regardless of which page/conversation the user is viewing.
 */

/**
 * User channel event names - must match backend ConversationEvents constants
 * @see backend/private-packages/von-pusher-service/von_pusher_service/events.py
 */
export const UserChannelEvents = {
  CONVERSATION_TITLE_UPDATED: "conversation_title_updated",
  DASHBOARD_REFRESH_STARTED: "dashboard_refresh_started",
  DASHBOARD_REFRESH_COMPLETED: "dashboard_refresh_completed",
  COMMAND_CREATED: "command_created",
} as const;

export type UserChannelEventName =
  (typeof UserChannelEvents)[keyof typeof UserChannelEvents];

/**
 * Sent when a conversation title is generated by the backend
 */
export interface ConversationTitleUpdatedEvent {
  conversationId: string;
  title: string;
  updatedAt: string;
}

/**
 * Sent when a dashboard refresh starts (background workflow initiated)
 */
export interface DashboardRefreshStartedEvent {
  dashboardId: string;
  executionId: string;
}

/**
 * Sent when a dashboard refresh completes (workflow finished successfully)
 */
export interface DashboardRefreshCompletedEvent {
  dashboardId: string;
  executionId: string;
  success: boolean;
}

/**
 * Sent when a quick command is created by the agent
 */
export interface CommandCreatedEvent {
  commandId: string;
  commandName: string;
  slug: string;
}

/**
 * Sent when org memory/context is updated (future use)
 */
export interface OrgMemoryUpdatedEvent {
  updatedAt: string;
  updatedBy?: string;
}

/**
 * Generic notification event (future use)
 */
export interface NotificationEvent {
  type: "info" | "success" | "warning" | "error";
  message: string;
  action?: {
    label: string;
    url: string;
  };
}
