/**
 * Event types for the user-level Pusher channel
 *
 * These events are sent to private-vonlabs-user-{tenantId}-{userId}
 * and received regardless of which page/conversation the user is viewing.
 */

/**
 * User channel event names - must match backend ConversationEvents constants
 * @see backend/private-packages/von-pusher-service/von_pusher_service/events.py
 */
export const UserChannelEvents = {
  CONVERSATION_TITLE_UPDATED: "conversation_title_updated",
  MEMORY_INSIGHT_CREATED: "memory_insight_created",
  // Future events:
  // ORG_MEMORY_UPDATED: "org_memory_updated",
  // NOTIFICATION: "notification",
} as const;

export type UserChannelEventName =
  (typeof UserChannelEvents)[keyof typeof UserChannelEvents];

/**
 * Sent when a conversation title is generated by the backend
 */
export interface ConversationTitleUpdatedEvent {
  conversationId: string;
  title: string;
  updatedAt: string;
}

/**
 * Sent when a new memory insight is extracted from user messages
 */
export interface MemoryInsightCreatedEvent {
  id: string;
  key: string;
  createdAt: string;
  notify: boolean;
}

/**
 * Sent when org memory/context is updated (future use)
 */
export interface OrgMemoryUpdatedEvent {
  updatedAt: string;
  updatedBy?: string;
}

/**
 * Generic notification event (future use)
 */
export interface NotificationEvent {
  type: "info" | "success" | "warning" | "error";
  message: string;
  action?: {
    label: string;
    url: string;
  };
}
