/**
 * Generate conversation title
 * Returns empty string - title will be generated by LLM on first message
 *
 * @returns Empty string (LLM will generate title on first message)
 */
export function generateConversationTitle(): string {
  return "";
}

/**
 * Get display title for conversation
 * Returns "New Chat" placeholder if title is empty
 *
 * Note: In normal flow, conversations with empty titles are filtered out
 * from the sidebar. This fallback handles edge cases where a conversation
 * might be displayed before title generation completes.
 *
 * @param title - Conversation title (may be empty)
 * @returns Display title (never empty)
 */
export function getDisplayTitle(title: string): string {
  return title && title.trim() !== "" ? title : "New Chat";
}
